# Generated by Django 5.2.1 on 2025-06-03 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.FileField(upload_to='tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpx'])])),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('moderado', 'Moderado'), ('dificil', 'Difícil')], default='moderado', max_length=10)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration should be in minutes', null=True)),
                ('route_type', models.CharField(choices=[('ida_volta', 'Ida e Volta'), ('ida', 'Ida'), ('volta', 'Volta')], default='ida_volta', max_length=10)),
                ('elevation', models.FloatField(blank=True, help_text='Elevation should be in meters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
