# Generated by Django 5.2.1 on 2025-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
