# Generated by Django 5.2.1 on 2025-06-13 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='distance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
