# Generated by Django 5.2.1 on 2025-06-13 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0005_track_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distance should be in meters', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
