# Generated by Django 5.2.1 on 2025-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0006_alter_track_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/images/'),
        ),
    ]
