# Generated by Django 5.2.1 on 2025-12-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0007_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='qdrant_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
